# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: true

warnings_are_errors: false

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev

r_github_packages: r-lib/pkgdown

before_install:
  - tlmgr install index

after_success:
  - Rscript -e 'covr::codecov()'

